services:
  - type: worker
    name: 99acres-lead-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 99acresLeadTracker:app
    envVars:
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
